# Generated by Django 3.2.8 on 2021-11-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaa', '0004_auto_20211128_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
